src/src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $Descripcion = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $Precio = null;

    #[ORM\Column(length: 255)]
    private ?string $Imagen = null;

    #[ORM\ManyToOne(inversedBy: 'productos')]
    private ?Categorias $categorias = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getPrecio(): ?string
    {
        return $this->Precio;
    }

    public function setPrecio(string $Precio): self
    {
        $this->Precio = $Precio;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen(string $Imagen): self
    {
        $this->Imagen = $Imagen;

        return $this;
    }

    public function getCategorias(): ?Categorias
    {
        return $this->categorias;
    }

    public function setCategorias(?Categorias $categorias): self
    {
        $this->categorias = $categorias;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CategoriasRepository;


class HomeController extends AbstractController
{
    #[Route('/home', name: 'app_home')]
    public function index(CategoriasRepository $categoriasRepository): Response
    {   
        $data = $categoriasRepository->findAll();
        return $this->render('home/index.html.twig', [
            'categorias' => $data
        ]);
    }

    #[Route('/home/cuerpoMedico', name: 'medicos')]
    public function cuerpoMedico(): Response
    {
        return $this->render('home/cuerpoMedico.html.twig');
    }

    #[Route('/home/balanceado', name: 'comida')]
    public function balanceado(): Response
    {
        return $this->render('home/balanceado.html.twig');
    }
}

templates/Home/cuerpoMedico.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Album example · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/album/">

    

    

<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

.frame {
  width: 90%;
  margin: 40px auto;
  text-align: center;
}
button {
  margin: 20px;
}
.custom-btn {
  width: 130px;
  height: 40px;
  color: #fff;
  border-radius: 5px;
  padding: 10px 25px;
  font-family: 'Lato', sans-serif;
  font-weight: 500;
  background: transparent;
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
  display: inline-block;
   box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
  outline: none;
}

.btn-12{
  position: relative;
  right: 20px;
  bottom: 20px;
  border:none;
  box-shadow: none;
  width: 130px;
  height: 40px;
  line-height: 42px;
  -webkit-perspective: 230px;
  perspective: 230px;
}
.btn-12 span {
  background: rgb(0,172,238);
background: linear-gradient(0deg, rgba(0,172,238,1) 0%, rgba(2,126,251,1) 100%);
  display: block;
  position: absolute;
  width: 130px;
  height: 40px;
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
  border-radius: 5px;
  margin:0;
  text-align: center;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: all .3s;
  transition: all .3s;
}
.btn-12 span:nth-child(1) {
  box-shadow:
   -7px -7px 20px 0px #fff9,
   -4px -4px 5px 0px #fff9,
   7px 7px 20px 0px #0002,
   4px 4px 5px 0px #0001;
  -webkit-transform: rotateX(90deg);
  -moz-transform: rotateX(90deg);
  transform: rotateX(90deg);
  -webkit-transform-origin: 50% 50% -20px;
  -moz-transform-origin: 50% 50% -20px;
  transform-origin: 50% 50% -20px;
}
.btn-12 span:nth-child(2) {
  -webkit-transform: rotateX(0deg);
  -moz-transform: rotateX(0deg);
  transform: rotateX(0deg);
  -webkit-transform-origin: 50% 50% -20px;
  -moz-transform-origin: 50% 50% -20px;
  transform-origin: 50% 50% -20px;
}
.btn-12:hover span:nth-child(1) {
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
  -webkit-transform: rotateX(0deg);
  -moz-transform: rotateX(0deg);
  transform: rotateX(0deg);
}
.btn-12:hover span:nth-child(2) {
  box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
   7px 7px 20px 0px rgba(0,0,0,.1),
   4px 4px 5px 0px rgba(0,0,0,.1);
 color: transparent;
  -webkit-transform: rotateX(-90deg);
  -moz-transform: rotateX(-90deg);
  transform: rotateX(-90deg);
}


</style>

    
  </head>
  <body>
    
<header>

</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Profesionales especializados</h1>
        <p class="lead text-muted">Te traemos a nuestros profesionales especializados en su area, ingresa y solicita tu turno con nostros.</p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{asset('images/rayosX.jfif')}}">
            <h5>Rayos X</h5>
            <div class="card-body">
              <p class="card-text">Consulta sobre nuestros profesionales en rayos y pide tu turno.</p>
              <div class="d-flex justify-content-between align-items-center flex-column">
              <!-- aca comienza el dropdown-->
                <p>
                  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample">
                    Telefonos
                  </button>
                </p>
                <div style="min-height: 120px;">
                  <div class="collapse" id="collapseWidthExample">
                    <ul class="list-group">
                      <li class="list-group-item">Juan garcia 221-555-222</li>
                      <li class="list-group-item">Perez Damian 221-555-777</li>
                      <li class="list-group-item">Larroque Maria 221-111-888</li>
                      <li class="list-group-item">Lape Aron 221-777-888</li>
                      <li class="list-group-item">Quiroga Luisa 011-777-888</li>
                    </ul>
                  </div>
                </div> <!-- aca termina el dropdown-->
              </div>
            </div>
          </div>
        </div>
        

        <div class="col">
          <div class="card shadow-sm">
           <img src="{{asset('images/eco.jfif')}}">
           <h5>Ecografias</h5>
            <div class="card-body">
              <p class="card-text">Consulta sobre nuestros profesionales en ecografias y pide tu turno.</p>
              <div class="d-flex justify-content-between align-items-center flex-column">
                <!-- aca comienza el dropdown-->
                <p>
                  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample2" aria-expanded="false" aria-controls="collapseWidthExample2">
                    Telefonos
                  </button>
                </p>
                <div style="min-height: 120px;">
                  <div class="collapse" id="collapseWidthExample2">
                    <ul class="list-group">
                      <li class="list-group-item">Juan garcia 221-555-222</li>
                      <li class="list-group-item">Perez Damian 221-555-777</li>
                      <li class="list-group-item">Larroque Maria 221-111-888</li>
                      <li class="list-group-item">Lape Aron 221-777-888</li>
                      <li class="list-group-item">Quiroga Luisa 011-777-888</li>
                    </ul>
                  </div>
                </div> <!-- aca termina el dropdown-->
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{{asset('images/lab.jpg')}}">
            <h5>Laboratorios</h5>
            <div class="card-body">
              <p class="card-text">Consulta sobre nuestros profesionales en laboratios y pide tu turno.</p>
              <div class="d-flex justify-content-between align-items-center flex-column">
                <!-- aca comienza el dropdown-->
                <p>
                  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample3" aria-expanded="false" aria-controls="collapseWidthExample3">
                    Telefonos
                  </button>
                </p>
                <div style="min-height: 120px;">
                  <div class="collapse" id="collapseWidthExample3">
                    <ul class="list-group">
                      <li class="list-group-item">Juan garcia 221-555-222</li>
                      <li class="list-group-item">Perez Damian 221-555-777</li>
                      <li class="list-group-item">Larroque Maria 221-111-888</li>
                      <li class="list-group-item">Lape Aron 221-777-888</li>
                      <li class="list-group-item">Quiroga Luisa 011-777-888</li>
                    </ul>
                  </div>
                </div> <!-- aca termina el dropdown-->
              </div>
            </div>
          </div>
        </div>        
  </div>


<div class="frame">
  <button class="custom-btn btn-12"><a class="text-light" href="/home"><span>Click!</span><span>Volver al home</span></a></button>
</div>


</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="mb-1">Esperemos que encuentres lo que estabas buscando</p>
  </div>
</footer>


    <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

      
  

</body>

</html>
{% endblock %}

templates/Home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}


{% block body %}


<style>

.fondo
{
background: #292929; 
background-image: 
url(https://www.phoenixmedical.com/media/logo/stores/2/Hi-Res_Logo_with_slogan.png);
background-size: cover;
color: #fff;
  
}

.jumbotron {
  background: #292929; 
  background-image: 
  /*url(https://croydonparkvet.com.au/wp-content/uploads/2017/05/Header-background-5.jpg);*/
   background-position: 90% 50%;
  background-size: 300px auto;
  background-repeat: no-repeat;
  
  color: #fff;
}

.jumbotron h1,p
 {
    text-align: center;
    
  }


.fondo{
background-image: 
url(https://croydonparkvet.com.au/wp-content/uploads/2017/05/Header-background-5.jpg);
background-position: 90% 50%;
background-size: fill;

}


/* titulo (web) (https://codepen.io/ArnaudBalland/pen/LZyvGZ) */

.intro{
  background: url(https://source.unsplash.com/cTO6DWSIdWI);
  background-size: cover;
  background-attachment: fixed;
  height: 100%;
}
    
  .content{
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    background: rgba(0,0,0,0.1);  
  }
    
    .header-group{
      background: rgba(0,0,0,0.2);
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);
      width: 550px;
      padding: 20px 50px;
      border: 4px solid #fff;
      font-family: $font;
      text-transform: uppercase;
      text-align: center;
      -moz-box-shadow: inset 0px 0px 2px 0px #2c3e50;
      -webkit-box-shadow: inset 0px 0px 2px 0px #2c3e50;
      -o-box-shadow: inset 0px 0px 2px 0px #2c3e50;
      box-shadow: inset 0px 0px 2px 0px #2c3e50;
      filter:progid:DXImageTransform.Microsoft.Shadow(color=#2c3e50, Direction=NaN, Strength=2);
      opacity: 0;
      -webkit-animation-name: fadeIn;
      animation-name: fadeIn;
      -webkit-animation-delay: 1s;
      animation-delay: 1s;
      -webkit-animation-duration: 2s;
      animation-duration: 2s;
      -webkit-animation-fill-mode: both;
      animation-fill-mode: both;
    }
      
      @keyframes fadeIn{
        0%{opacity:0;}
        100%{opacity:1;}
      }

      .header-title{
        color: #fff;
        font-size: 5em;
        text-shadow: 5px 2px $bg-color-1;
      }

</style>

<body> 

<main>
  
  <div class="fondo position-relative overflow-hidden p-3 p-md-5 text-center bg-info text-dark">

    <nav class="container d-flex flex-column flex-md-row justify-content-between">
    
    <a class="py-2" href="#" aria-label="Product">
    
      <i class="fa-regular fa-hospital fs-3 position-absolute top-0 start-0" ></i>
    </a>
    </nav>

    {# <a
      class="inline-block text-gray-300 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"
      href="/{{ app.user ? 'logout' : 'login' }}"
      @click="isOpen = false">
      {{ app.user ? 'Logout' : 'Login' }}
    </a> #}

  
  <div class="col-md-1 p-lg-5  my-5">
    <div class="intro ">
    <div class="content">
    <div class="header-group"> 
    <h1 class="header-title display-4 fw-normal text-light">Veterinaria</h1>
      <p class="lead fw-normal text-light ">Registrate y logeate para poder comprar o hacer consultas online para tu mascota</p>
  <a
    class="btn btn-primary"
    href="/{{ app.user ? 'logout' : 'login' }}"
    @click="isOpen = false">
    {{ app.user ? 'Logout' : 'Login' }}
  </a>

  {% if not app.user %}
    <a
      class="btn btn-primary"
      href="/register">Register
    </a> 
  {% endif %}
  
    </div>
    </div>
    </div> 
    {# <a class="btn btn-outline-secondary" href="/login">Login</a> #}
    {# <a class="btn btn-outline-secondary" href="/register">Registrarse</a> #}
  </div>


<div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  </div>
</div>
  

 
<div class="jumbotron jumbotron-fluid  p-3 m-md-1">
  <div class="container text-xs-center">
    <h1 class="display-1">Sobre nosotros</h1>
    <p class="lead">Descripccion.</p>
  </div>
</div>



  {# <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h1 class="display-4 fw-normal">Sobre nosotros</h1>
    <p class="lead fw-normal">Descripción</p>
    <button type="button" class="btn btn-sm btn-outline-secondary"><a class="" href="#">View</button></a>
  </div> #}


  <div class="col-md-5 p-lg-5 mx-auto my-5 d-flex flex-column align-items-center">
    <h1 class="display-4 fw-normal">Medicos especializados</h1>
    <p class="lead fw-normal">Descripción</p>
    {# <button type="button" class="btn btn-sm btn-outline-secondary position-absolute top-100 start-50 translate-middle ">
      <a class="inline-block text-gray-300 no-underline hover:text-gray-200 hover:text-underline py-4 px-4 " href="/home/cuerpoMedico">View
    </button> #}
    <a href="/home/cuerpoMedico" class="btn btn-primary ">Read More</a>
    
  </div>





<!-- Vista de los productos y categorias -->


  <div class="album p-3 mb-2 bg-primary text-dark">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for categoria in categorias %}
        <div class="col">
          <div class="card shadow-sm">
          <img src="/uploads/{{categoria.imagen}}">
            <title>{{categoria.Nombre}}</title><rect width="100%" height="100%" fill="#55595c"></rect>
            <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{categoria.Nombre}}</text></svg>
            <div class="card-body">
              <p class="card-text">{{categoria.descripcion|raw}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="/categorias/{{categoria.id}}" class="btn btn-primary">
                    Ver
                </a>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div> 
        {% endfor %}      
      </div>
    </div>
  </div>




<!-- Comienza el footer -->

<footer class="container py-5"> 
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-heart-pulse-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1.475 9C2.702 10.84 4.779 12.871 8 15c3.221-2.129 5.298-4.16 6.525-6H12a.5.5 0 0 1-.464-.314l-1.457-3.642-1.598 5.593a.5.5 0 0 1-.945.049L5.889 6.568l-1.473 2.21A.5.5 0 0 1 4 9H1.475ZM.879 8C-2.426 1.68 4.41-2 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C11.59-2 18.426 1.68 15.12 8h-2.783l-1.874-4.686a.5.5 0 0 0-.945. 049L7.921 8.956 6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8H.88Z"/>
      </svg>
      <small class="d-block mb-3 text-muted">© 2017–2022</small>
    </div>
    <div class="col-6 col-md">
      <h5>Tienda</h5>
      <ul class="list-unstyled text-small">
        {# <li><a class="link-secondary" href="#">Cool stuff</a></li>
        <li><a class="link-secondary" href="#">Random feature</a></li>
        <li><a class="link-secondary" href="#">Team feature</a></li>
        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
        <li><a class="link-secondary" href="#">Another one</a></li>
        <li><a class="link-secondary" href="#">Last time</a></li> #}
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Explorar</h5>
      <ul class="list-unstyled text-small">
        {# <li><a class="link-secondary" href="#">Resource name</a></li>
        <li><a class="link-secondary" href="#">Resource</a></li>
        <li><a class="link-secondary" href="#">Another resource</a></li>
        <li><a class="link-secondary" href="#">Final resource</a></li> #}
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Social</h5>
      <ul class="list-unstyled text-small">
        {# <li><a class="link-secondary" href="#">Business</a></li>
        <li><a class="link-secondary" href="#">Education</a></li>
        <li><a class="link-secondary" href="#">Government</a></li>
        <li><a class="link-secondary" href="#">Gaming</a></li> #}
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Soporte</h5>
      <ul class="list-unstyled text-small">
        {# <li><a class="link-secondary" href="#">Team</a></li>
        <li><a class="link-secondary" href="#">Locations</a></li>
        <li><a class="link-secondary" href="#">Privacy</a></li>
        <li><a class="link-secondary" href="#">Terms</a></li> #}
      </ul>
    </div>
  </div>
</footer>


</body>


{% endblock %}